# Generated by Django 3.1.2 on 2020-10-17 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100, verbose_name='primera dirección')),
                ('address2', models.CharField(max_length=100, verbose_name='segunda dirección')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('country', models.CharField(max_length=50, verbose_name='país')),
                ('postcode', models.CharField(max_length=50, verbose_name='código postal')),
                ('state', models.CharField(max_length=50, verbose_name='estado')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='longitud')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=50, verbose_name='lunes')),
                ('tuesday', models.CharField(max_length=50, verbose_name='martes')),
                ('wednesday', models.CharField(max_length=50, verbose_name='miércoles')),
                ('thursday', models.CharField(max_length=50, verbose_name='jueves')),
                ('friday', models.CharField(max_length=50, verbose_name='viernes')),
                ('saturday', models.CharField(max_length=50, verbose_name='sábado')),
                ('sunday', models.CharField(max_length=50, verbose_name='domingo')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=50, verbose_name='facebook')),
                ('instagram', models.CharField(max_length=50, verbose_name='instagram')),
                ('pinterest', models.CharField(max_length=50, verbose_name='pinterest')),
                ('twitter', models.CharField(max_length=50, verbose_name='twitter')),
                ('youtube', models.CharField(max_length=50, verbose_name='youtube')),
            ],
            options={
                'verbose_name': 'redes sociales',
                'verbose_name_plural': 'redes sociales',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='teléfono')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
                ('website', models.CharField(max_length=50, verbose_name='sitio web')),
                ('image', models.ImageField(upload_to='organization', verbose_name='imagen')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.address', verbose_name='dirección')),
                ('hours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.hour', verbose_name='horario')),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.socialmedia', verbose_name='redes sociales')),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
            },
        ),
    ]
