name: Python Code Coverage Workflow
on:
  push:
    branches:
      - 'master'
      - 'develop'
        
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2.3.3
      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2.1.2 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.x # if you want multiple python version run just use matrix strategy in job config. See the documentation of GitHub Actions
      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version
      - name: Install requirements # install application requirements
        run: pip install -r requirements.txt
      - name: Install env file
        env:
          ENV_FILE_DEV: ${{ secrets.ENV_FILE_DEV }}
        run: 'echo "$ENV_FILE_DEV" > ./app/settings/.env'
      - name: Generate coverage report
        run: pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
